version: '3.8'

services:
  # Контейнер Web-Server
  webserver:
    image: gorcomcomputing/webserver:latest
    ports:
      - "80:80"  # Переопределение порта: внешний 8080 -> внутренний 8080
    networks:
      - mynetwork   # Название сети для взаимодействия с другими контейнерами
      
networks:
  mynetwork:  # Определение пользовательской сети для взаимодействия контейнеров

