version: '3.8'

services:
  # Контейнер AON
  aon:
    image: aon:latest
    ports:
      - "8080:8080"  # Переопределение порта: внешний 8080 -> внутренний 8080
    networks:
      - mynetwork   # Название сети для взаимодействия с другими контейнерами
      
networks:
  mynetwork:  # Определение пользовательской сети для взаимодействия контейнеров

